apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-zuz6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbow-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-zuz6@sha256:40046e30e13be40f6aee3436a592caa378d5bb3fa8ab58a125150bcbe99419e7
        name: my-go
        resources: {}
status: {}
