apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-txly
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbow-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-txly@sha256:10d44166d0932a5e0de84b99bb4006a0f1258004399027bc9ce672377e7a4ebc
        name: my-nodejs
        resources: {}
status: {}
